
# Global options
baseURL = "/"
canonifyURLs = true
copyright = "© 2021 by Nicola Rustignoli. <a href='/privacy'>Privacy policy</a>."
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "Nicola Rustignoli"



# Main menu
[[menu.main]]
    name = "About"
    url  = "/"
    weight = 2
[[menu.main]]
    name = "Talks - Articles"
    url  = "/talks"
    weight = 2
#[[menu.main]]
#    name = "Blog"
#    url  = "/posts"
#    weight = 3



# Customization options
[params]

    [params.head]
        author = "Nicola Rustignoli"
        custom_css = ""
        description = "Random network security, cloud and tech stuff"
        keywords = ["engineering", "SCION", "network security", "SD-WAN"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Bree Serif"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#264653"
        link_color = "#2a9d8f"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:nicola.rustignoli@inf.ethz.ch"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/nicorusti"
            weight = 2
#        [params.social.google_scholar]
#            name = "Google Scholar"
#            class = "ai ai-google-scholar-square"
#            url = ""
#            weight = 3
#        [params.social.instagram]
#            name = "Instagram"
#            class = "fab fa-instagram"
#            url = ""
#            weight = 4
# For icons, fontawesome.com, academicons https://jpswalsh.github.io/academicons/ 
# https://fontawesome.com/v5.15/icons?d=gallery&p=2
        [params.social.institution]
            name = "ETH Zürich"
            class = "fas fa-university"
            url = "https://netsec.ethz.ch/"
            weight = 5
        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://www.linkedin.com/in/nicola-rustignoli-830b7512/"
            weight = 6
        [params.social.twitter]
            name = "Twitter"
            class = "fab fa-twitter"
            url = "https://twitter.com/Nicorusti"
            weight = 8



# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'
